# Generated by Django 4.1.2 on 2022-10-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_basket_number_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 16, 30, 36, 252735)),
        ),
    ]
