# Generated by Django 4.1.2 on 2022-10-26 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_discount_expire_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 31, 12, 610330)),
        ),
        migrations.AlterField(
            model_name='registreduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
