# Generated by Django 4.1.2 on 2022-10-26 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_discount_expire_alter_registreduser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('allowed_amount_to_substract', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 18, 24, 38, 963091)),
        ),
        migrations.AlterField(
            model_name='registreduser',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
